Jira connector
dataiku/dss-plugin-jira pull request #1
Opened 2020-04-16 15:58 UTC by alexbourret

2020-10-16 14:14 UTC, MayeulRousselet requested changes
I think it lacks some documentation about the endpoint abstraction:
- what is COLUMN_FORMATING, COLUMN_EXPANDING...

2020-10-16 14:14 UTC, MayeulRousselet commented on custom-recipes/jira-services/recipe.json
> +        "description": "Retrieve Jira data based on IDs from the input dataset",
Be more specific in the description

2020-10-16 14:14 UTC, MayeulRousselet commented on custom-recipes/jira-services/recipe.json
> +            "description": "what main output means",
To be changed?

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_api.py
> +API = "api"
I think this file should be splitted in two:
- a jira_api_constants.y with all the constants
- a jira_api_schema.py with the descriptors

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_api.py
> +    "endpoint_name": {
should be renamed: endpoints

2020-10-16 14:14 UTC, MayeulRousselet commented on python-connectors/jira/connector.py
> +        self.connection_details = self.config.get(self.access_type)
self.connection_details is used afterward, can be deleted

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        self.connection_details = connection_details
self. connection_details is not used afterwards, is it really necessary to store it?

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        self.api = jira_api
Not very fond of this, to store a module as a class field.
Better to use `import jira_api as api` and to replace `self.api.X` by `api.X`

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +    def normalize_url(self, url):
Can be moved out of the class as the function doesn't use self

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        endpoint_descriptor = copy.deepcopy(self.api.endpoint_descriptors[self.api.API_DEFAULT_DESCRIPTOR])
if we decide that the supported python version will be >= 3.5, we could then use the dict merge operation :
```
endpoint_descriptor = {**self.api.endpoint_descriptors[self.api.API_DEFAULT_DESCRIPTOR], **self.api.endpoint_descriptors[self.api.API_ENDPOINT_NAME][endpoint_name])
```

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        endpoint_descriptor = self.get_endpoint_descriptor(endpoint_name)
`endpoint_descriptor = self.get_endpoint_descriptor(endpoint_name)` is called several times, and each time we merge two dictionaries. Could it be possible to cache the merge operation result (therefore the real endpoint descriptor) into a dictionary?

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +class JiraClient(object):
Alors attention, gros commentaire. 
Pour plus de clareté (et de réusabilité), je splitterais la classe JiraClient en 2:
- Une classe Endpoint
- Une classe Jiraclient, avec un endpoint comme membre.

Pourquoi? Ca permettrait de déplacer tout le code generique d'interpretation du dict endpoint_descriptor dans une classe dédiée et de n'avoir que des traitements specifiques dans JiraClient.
Donc en gros Endpoint aurait les methodes suivantes:
- start_session
- get_url
- get_resource_name
- get_ressource_structure
- get_endpoint (avec une adaptation pour gérer le formatting de l'exception)
- start_paging
- get_params
- get_query_string_dict
- get_pagination_config
- get_endpoint_descriptor
- ...

De plus, toutes les classes comme qui ne font que du nettoyage de data etc sans utiliser des champs du JiraClient ni les champs du Endpoint devrait etre deplacés en dehors je pense.

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        params = {} if params is None else params
Better to define a default value for the params param:
```
params={}
```

2020-10-16 14:14 UTC, MayeulRousselet commented on python-lib/pagination.py
> +    def __init__(self, config=None, skip_key=None, limit_key=None, total_key=None, next_page_key=None):
the params aren't used, why declare them?

2020-10-16 15:21 UTC, alexbourret commented on python-lib/jira_api.py
> +API = "api"
As discussed, the constants are used mostly in the descriptors, and we're not allowed to import *, so it would make the resulting code heavier.

2020-10-19 09:41 UTC, alexbourret commented on python-lib/jira_client.py
> +        params = {} if params is None else params
So I thought but then Sonar told me it's bad practice (S5717)...
params is modified within the function and yet would be shared by other instances, which could lead to weird bugs

2020-10-19 09:45 UTC, MayeulRousselet commented on python-lib/jira_client.py
> +        params = {} if params is None else params
Ok my bad!

2020-10-19 09:54 UTC, alexbourret commented on python-lib/jira_client.py
> +class JiraClient(object):
As discussed, further use of generic endpoint class will re use what is being developed for the rest-api plugin.

2020-11-19 15:51 UTC, merged